install scripts using setuptools
- lookup.py was deprecated in favor of setuptools entry_points; the code for
  lookup.py was moved to django_sshkey.util.lookup_main
- lookup.sh was renamed to django-sshkey-lookup since setuptools retains the
  names of scripts once installed. A symlink has been left in place.

diff --git a/django-sshkey-lookup b/django-sshkey-lookup
--- a/django-sshkey-lookup
+++ b/django-sshkey-lookup
@@ -1,4 +1,4 @@
-#!/usr/bin/env python
+#!/bin/bash
 # Copyright 2013 Scott Duckworth
 #
 # This file is part of django-sshkey.
@@ -16,9 +16,15 @@
 # You should have received a copy of the GNU Lesser General Public License
 # along with django-sshkey.  If not, see <http://www.gnu.org/licenses/>.
 
-import warnings
-import django_sshkey.util
-
-warnings.warn("lookup.py is deprecated; use django-sshkey-pylookup",
-              DeprecationWarning)
-django_sshkey.util.lookup_main()
+url="$1"
+if [ $# -eq 1 ]; then
+  read line
+  fingerprint=$(ssh-keygen -lf /dev/stdin <<< $line | cut -f2 -d' ')
+  exec curl -s -G "$url" --data-urlencode "fingerprint=${fingerprint}"
+elif [ $# -eq 2 ]; then
+  username="$2"
+  exec curl -s -G "$url" --data-urlencode "username=${username}"
+else
+  echo "Invalid number of arguments" >&2
+  exit 2
+fi
